{% set name = "time-machine" %}
{% set version = "3.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-3.2.0.tar.gz
    sha256: a4ddd1cea17b8950e462d1805a42b20c81eb9aafc8f66b392dd5ce997e037d79
  - folder: src_for_test
    url: https://github.com/adamchainz/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: c74880a913e25b30de6be7645fa81b8ff374f0332dbbfd6c22d9445729cee637

build:
  skip: true  # [py<310]
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=77
  run:
    - python
    - python-dateutil

test:
  source_files:
    - src_for_test/tests
    - src_for_test/pyproject.toml
  imports:
    - time_machine
  commands:
    - pip check
    # Skip tests on windows - AttributeError: module 'time' has no attribute 'tzset'
    # ModuleNotFoundError: No module named 'tokenize_rt'
    - pytest -v src_for_test/tests --ignore=src_for_test/tests/test_cli.py # [not win]
  requires:
    - pip
    - coverage
    - pytest
    - freezegun
    - pytest-randomly
    - python-dateutil

about:
  home: https://github.com/adamchainz/time-machine
  summary: Travel through time in your tests.
  description: |
    time-machine is intended to combine the advantages of freezegun and libfaketime. It works without LD_PRELOAD but
    still mocks the standard library functions everywhere they may be referenced. It does so by modifying the built-in
    functions at the C level, to point them through wrappers that return different values when mocking. Normally in
    Python, built-in functions are immutable, but time-machine overcomes this by using C code to replace their function
    pointers.
  license: MIT
  license_file: dist/LICENSE
  license_family: MIT
  doc_url: https://adamj.eu/tech/2020/06/03/introducing-time-machine/
  dev_url: https://github.com/adamchainz/time-machine

extra:
  recipe-maintainers:
    - bollwyvl
